# Generated by Django 2.2.11 on 2020-03-25 07:05

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200325_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
