# Generated by Django 2.2.11 on 2020-03-25 09:50

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=django_google_maps.fields.AddressField(default=1213, max_length=200),
            preserve_default=False,
        ),
    ]
