# Generated by Django 2.2.11 on 2020-03-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
